_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  better_exposed_filters: 0
  blazy: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  captcha: 0
  ckeditor5: 0
  ckeditor_media_image_style: 0
  clamav: 0
  coffee: 0
  config: 0
  config_split: 0
  config_update: 0
  contextual: 0
  crop: 0
  csv_serialization: 0
  custom_pub: 0
  date_popup: 0
  date_recur: 0
  date_recur_modular: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  diff: 0
  draggableviews: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  environment_indicator: 0
  exif_orientation: 0
  facets: 0
  facets_exposed_filters: 0
  facets_pretty_paths: 0
  facets_searchbox_widget: 0
  field: 0
  field_group: 0
  field_group_layout: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  gin_toolbar: 0
  google_tag: 0
  help: 0
  history: 0
  hux: 0
  image: 0
  inline_form_errors: 0
  integration_report: 0
  js_cookie: 0
  jsonapi: 0
  jsonapi_extras: 0
  lagoon_logs: 0
  language: 0
  layout_discovery: 0
  layout_paragraphs: 0
  layout_paragraphs_permissions: 0
  link: 0
  linkit: 0
  masquerade: 0
  media: 0
  media_entity_file_replace: 0
  media_file_delete: 0
  media_library: 0
  media_remote_audio: 0
  media_responsive_thumbnail: 0
  media_thumbnail_url_formatter: 0
  menu_block: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  migrate: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_limits: 0
  path: 0
  path_alias: 0
  pbs_core: 0
  pbs_event: 0
  pbs_interview: 0
  pbs_migrate: 0
  pbs_news: 0
  pbs_page: 0
  pbs_refreshless: 0
  pbs_search: 0
  pbs_video: 0
  queue_ui: 0
  rabbit_hole: 0
  radio_station: 0
  radio_station_omnystudio: 0
  recaptcha_v3: 0
  redirect: 0
  redis: 0
  refreshless: 0
  refreshless_turbo: 0
  reroute_email: 0
  responsive_image: 0
  rest: 0
  robotstxt: 0
  role_delegation: 0
  schema_article: 0
  schema_event: 0
  schema_metatag: 0
  schema_movie: 0
  schema_video_object: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_solr: 0
  search_api_solr_autocomplete: 0
  seckit: 0
  serialization: 0
  shield: 0
  simpleads: 0
  slick: 0
  slick_ui: 0
  slick_views: 0
  smart_date: 0
  smart_trim: 0
  stage_file_proxy: 0
  storybook: 0
  style_options: 0
  system: 0
  taxonomy: 0
  text: 0
  time_field: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  ultimate_cron: 0
  user: 0
  vbo_export: 0
  view_unpublished: 0
  views_bootstrap: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  webform_views: 0
  workbench_access: 0
  workflows: 0
  workflows_field: 0
  extlink: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  claro: 0
  gin: 0
  radix: 0
  pbs: 0
profile: standard
