client:
  timeout: 300
  connect_timeout: 60
  send_read_requests: true
  send_create_requests: true
  send_update_requests: true
  send_delete_requests: false
  throttle_requests: 8
  throttle_period: 15
active_provider: omnystudio
fallback_episode_author: 'Radio Station'
recording_start_offset_seconds: 29
recording_end_offset_seconds: 180
future_episode_cron_interval_minutes: 15
future_episode_schedule_slot_match_threshold_minutes: 15
future_episode_weeks_in_advance: 2
logging:
  matcher: true
  future_episodes: true
  api_client: true
  sync: true
  webhook: true
  acl: false
  timeline: false
