_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: cf110b0b-0131-428d-86dd-b2ac7ae89ca8
name: PBS
mail: alex+pbs@drevops.com
slogan: 'Amplifying under-represented music & supporting the local music community'
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
